[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip nRF52840"

# rustflags = [
#     "-C",
#     "link-arg=--nmagic",
#     "-C",
#     "link-arg=-Tlink.x",
#     "-C",
#     "link-arg=-Tdefmt.x",

#     # Code-size optimizations.
#     #   trap unreachable can save a lot of space, but requires nightly compiler.
#     #   uncomment the next line if you wish to enable it
#     # "-Z", "trap-unreachable=no",
#     "-C",
#     "inline-threshold=5",
#     "-C",
#     "no-vectorize-loops",
# ]

[build]
# Pick ONE of these compilation targets
# target = "thumbv6m-none-eabi"    # Cortex-M0 and Cortex-M0+
# target = "thumbv7m-none-eabi"    # Cortex-M3
# target = "thumbv7em-none-eabi" # Cortex-M4 and Cortex-M7 (no FPU)
target = "thumbv7em-none-eabihf" # Cortex-M4F and Cortex-M7F (with FPU)

[env]
DEFMT_LOG = "info"
